/*
Date 4/20/2017
Ricky Gutierrez
CSC134
Homework 3
*/
CREATE TABLE COURSE
(
CourseNo CHAR(6) NOT NULL,
CourseName VARCHAR(32) NOT NULL,
Department VARCHAR(32) NOT NULL,
PRIMARY KEY (CourseNo)
);

CREATE TABLE SECTION
(
CourseNo CHAR(6) NOT NULL,
SectionNo INT NOT NULL,
Instructor VARCHAR(32) NOT NULL,
PRIMARY KEY (CourseNo, SectionNo)
);

CREATE TABLE ENROLLS
(
SSN CHAR(9) NOT NULL,
CourseNo CHAR(6) NOT NULL,
SectionNo INT NOT NULL,
PRIMARY KEY (SSN, CourseNo, SectionNo)
);

CREATE TABLE STUDENT
(
SSN CHAR(9) NOT NULL,
LastName VARCHAR(32) NOT NULL,
FirstName VARCHAR(32) NOT NULL,
Street VARCHAR(32) NOT NULL,
City VARCHAR(32) NOT NULL,
State CHAR(2) NOT NULL,
Zip CHAR(6) NOT NULL,
PRIMARY KEY (SSN)
);

CREATE TABLE TAKES
(
SSN CHAR(9) NOT NULL,
CourseNo CHAR(6) NOT NULL,
SectionNo INT NOT NULL,
ExamNo INT NOT NULL,
Result CHAR(1) NOT NULL,
PRIMARY KEY (SSN, CourseNo, SectionNo, ExamNo)
);

CREATE TABLE EXAM
(
CourseNo VARCHAR(6) NOT NULL,
SectionNo INT NOT NULL,
ExamNo INT NOT NULL,
E_Date CHAR(8) NOT NULL,
E_Time VARCHAR(5) NOT NULL,
PRIMARY KEY (CourseNo, SectionNo, ExamNo)
);

CREATE TABLE CONDUCTEDIN
(
RoomNo VARCHAR(6) NOT NULL,
Building VARCHAR(32) NOT NULL,
CourseNo CHAR(6) NOT NULL,
SectionNo INT NOT NULL,
ExamNo INT NOT NULL,
PRIMARY KEY (RoomNo, Building, CourseNo, SectionNo, ExamNo)
);

CREATE TABLE CLASSROOM
(
RoomNo VARCHAR(6) NOT NULL,
Building VARCHAR(32) NOT NULL,
Capacity INT NOT NULL,
PRIMARY KEY (RoomNo, Building)
);

/* Section */
ALTER TABLE SECTION ADD CONSTRAINT Fk_CourseNo FOREIGN KEY (CourseNo) REFERENCES COURSE(CourseNo);
/*Enrolls*/
ALTER TABLE ENROLLS ADD CONSTRAINT Fk_SSN FOREIGN KEY (SSN) REFERENCES STUDENT(SSN);
ALTER TABLE ENROLLS ADD CONSTRAINT Fk_CS FOREIGN KEY (CourseNo, SectionNo) REFERENCES SECTION(CourseNo, SectionNo);
/*Takes*/
ALTER TABLE TAKES ADD CONSTRAINT Fk_SSN1 FOREIGN KEY (SSN) REFERENCES STUDENT(SSN);
ALTER TABLE TAKES ADD CONSTRAINT Fk_CSE FOREIGN KEY (CourseNo, SectionNo, ExamNo) REFERENCES EXAM(CourseNo, SectionNo, ExamNo);
/*ConductedIn*/
ALTER TABLE CONDUCTEDIN ADD CONSTRAINT Fk_RB FOREIGN KEY (RoomNo, Building) REFERENCES CLASSROOM(RoomNo, Building);
/*ALTER TABLE CONDUCTEDIN ADD CONSTRAINT Fk_CSE1 FOREIGN KEY (CourseNo, SectionNo, ExamNo) REFERENCES EXAM(CourseNo, SectionNo, ExamNo);*/